sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZuK+Aqq/s5bKNTUOlpbv+J0vQQSfBVBCo+6qqpOay8l1flliNiK6EvGSWZjyPMT4+0W9WomHBB4RAVLQSfaLDddPl7XXXWt64LPSzz1gcFK6ozIst7BiYnDT9Dy21cpWr9+ABIzQkZH9/i1XNxgWyn3WCsrmBOvJ2lNMWplyU9sIBZT6EE+REx6QDOr7UACLGn21Lie5sT5A44BbPLq46MIZJpmqPnOjnNsYWkCgorCACoNv6tuAtdVWN9xqyIbU21MTM32ojv/v6ln/HJIdpEXMrfzzSDs6aeWIo4YkD9RYGptoNHa/9aYVZjHPzZsFHV6cfgS7+D06RIK86ID/LImzFzQIFR8ez3nlxmT6zMW6v8LFDXohgkDuIw/cGvQdAIkc7vq0bEiUSHDm8xo1QUGH0WbpCMFLJ++/R/9X7AYPXve9vhSFuEUStjW9Vj3EwYQRjjKYxe7U/jdk6gmWdFjj5gZnwg/MRmsXLj5oVkgk9GGfSz02pPWJrHS3oQaLpd1xIUDPogREZwr4hJG+NF+neAZXNfbffxUfM0DL3ChkxDQMaN96LkhK43T0wjsY70EUZK7rcr3wNxMoCc5gOXDhmYhK/uMlOrF0Zv8QA2abwYsp1JCc/aJHtls+IkI5AVjlXxYO5j8mWTIaacnkr1VYVKO6jzpJAt61e/khvc8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-London-Prodigal-by-William-Shakespeare-as-it-was-played-by-the-King-s-Majesties-servants_4031
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy